version: "3.9"

networks:
  db_net:

services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - db_net

  django_app:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
    ports:
      - "8080:8080"
    networks:
      - db_net